### ISSUE TITLE
ESP8266 GCC7 & 

### ISSUE THREAD

**Issue by luzidchris** [FatihBAKIR/toolchains#1]
Hi!

I have a question related to your attempts to build GCC7 for ESP8266. I'm currently trying to build a GCC toolchain with Ada support (GCC7.3.0) and faced the same problem you described here: https://github.com/jcmvbkbc/gcc-xtensa/issues/10
Any build seems to be done for big endianess, although I applied the overlays for xtensa-lx106. Did you resolve this issue? If so, what did you do to get rid of it? Maybe you could point me to the right direction.

Thanks in advance.

Chris

**Comment by luzidchris** [comment]
FYI, I now got a GCC7-based toolchain which is capable to build esp-open-sdk and esp-open-rtos. The following repo provides all what's required:
https://github.com/espway/esp8266-toolchain-docker

To add Ada support, I followed instructions of https://github.com/RREE/esp8266-ada/wiki/Steps-for-building-on-Linux

So, I guess there's no need to answer my request anymore.

**Comment by FatihBAKIR** [comment]
Sorry, I didn't check my notifications for a while.
